spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 47.99.243.32:8848
      discovery:
        server-addr: 47.99.243.32:8848
      config:
        server-addr: 47.99.243.32:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-authorize
          uri: lb://authorize
          predicates:
            - Path=/authorize/**
          filters:
            - StripPrefix=1
        - id: api-consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
        - id: api-provider
          uri: lb://provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
server:
  port: 61310